controller_manager:
  ros__parameters:
    update_rate: 100
    enforce_command_limits: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

left_arm_controller:
  ros__parameters:
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      left_s0: {trajectory: 0.2, goal: 0.02}
      left_s1: {trajectory: 0.2, goal: 0.02}
      left_e0: {trajectory: 0.2, goal: 0.02}
      left_e1: {trajectory: 0.2, goal: 0.02}
      left_w0: {trajectory: 0.2, goal: 0.02}
      left_w1: {trajectory: 0.2, goal: 0.02}
      left_w2: {trajectory: 0.2, goal: 0.02}

right_arm_controller:
  ros__parameters:
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      right_s0: {trajectory: 0.2, goal: 0.02}
      right_s1: {trajectory: 0.2, goal: 0.02}
      right_e0: {trajectory: 0.2, goal: 0.02}
      right_e1: {trajectory: 0.2, goal: 0.02}
      right_w0: {trajectory: 0.2, goal: 0.02}
      right_w1: {trajectory: 0.2, goal: 0.02}
      right_w2: {trajectory: 0.2, goal: 0.02}
